import type { EditExplanation, StructuredProjectEdit } from "../../../types/conversationEditor";
import type { UniversalComponent, UniversalWoodProject } from "../../../types/universalProject";
import { resolveEditTarget } from "./validator";

const inch = (value: number) => ({ value: Number(value.toFixed(3)), unit: "in" as const });
function dimensionValue(project: UniversalWoodProject, axis: "length" | "width" | "depth" | "height") { const measure = axis === "depth" ? project.dimensions.depth ?? project.dimensions.width : project.dimensions[axis]; if (!measure) return 0; return measure.unit === "ft" ? measure.value * 12 : measure.unit === "mm" ? measure.value / 25.4 : measure.unit === "cm" ? measure.value / 2.54 : measure.value; }
function replaceTag(tags: string[], prefix: string, value: string) { return [...tags.filter((tag) => !tag.startsWith(prefix)), `${prefix}${value}`]; }
function storageComponent(edit: Extract<StructuredProjectEdit, { type: "storage-change" }>, index: number, project: UniversalWoodProject): UniversalComponent { const materialId = project.materials[0]?.id ?? "material-direction"; const type = edit.storageType; return { id: `conversation-${type}-${edit.id}-${index + 1}`, name: `${type[0]!.toUpperCase()}${type.slice(1)} ${index + 1}`, role: "Conversation-added conceptual storage", quantity: 1, dimensions: type === "shelf" ? { length: inch(30), width: inch(12), height: inch(0.75) } : { length: inch(18), width: inch(16), height: inch(type === "door" ? 30 : 6) }, materialIds: [materialId], cutItemIds: [], structuralRole: "none" }; }

export function applyProjectEdits(original: UniversalWoodProject, edits: StructuredProjectEdit[]): { project: UniversalWoodProject; explanation: EditExplanation } {
  let project: UniversalWoodProject = structuredClone(original); const changes: string[] = []; const tradeoffs: string[] = []; const concerns: string[] = []; const editedIds = new Set<string>(); let status: "updated" | "added" | "removed" | "modified" = "modified";
  for (const edit of edits) {
    if (edit.type === "dimension-change") { const before = dimensionValue(project, edit.axis); const after = edit.operation === "delta" ? before + edit.value : edit.operation === "maximum" ? Math.min(before, edit.value) : edit.value; project = { ...project, dimensions: { ...project.dimensions, [edit.axis]: inch(after) } }; changes.push(`${edit.axis} changed from ${before} to ${after} inches.`); tradeoffs.push("Changing overall proportions may affect component spacing and future deterministic calculations."); editedIds.add("*"); status = "updated"; }
    else if (edit.type === "material-change") { const before = project.materials.map((material) => material.name).join(", ") || "unspecified material"; project = { ...project, materials: project.materials.map((material) => ({ ...material, name: edit.material, species: edit.material, treatment: edit.material === "pressure-treated" ? "pressure-treated" : undefined })) }; changes.push(`Material changed from ${before} to ${edit.material}.`); tradeoffs.push("Material choice can change price, weather resistance, weight, and finishing needs."); editedIds.add("*"); }
    else if (edit.type === "finish-change") { project = { ...project, materials: project.materials.map((material) => ({ ...material, finish: edit.finish })) }; changes.push(`Finish changed to ${edit.finish.replaceAll("-", " ")}.`); editedIds.add("*"); }
    else if (edit.type === "style-change") { project = { ...project, metadata: { ...project.metadata, style: edit.style } }; changes.push(`Style direction changed to ${edit.style}.`); editedIds.add("*"); }
    else if (edit.type === "environment-change") { project = { ...project, environment: { ...project.environment, location: edit.environment } }; changes.push(`Environment changed to ${edit.environment}.`); concerns.push("Material and finish suitability should be rechecked for the new environment."); }
    else if (edit.type === "component-add") { const additions = Array.from({ length: edit.quantity }, (_, index): UniversalComponent => ({ id: `conversation-${edit.componentType}-${edit.id}-${index + 1}`, name: `${edit.componentType} ${index + 1}`, role: "Conversation-added conceptual component", quantity: 1, materialIds: [project.materials[0]?.id ?? "material-direction"], cutItemIds: [], structuralRole: "none" })); project = { ...project, components: [...project.components, ...additions] }; additions.forEach((item) => editedIds.add(item.id)); changes.push(`Added ${edit.quantity} conceptual ${edit.componentType} component${edit.quantity === 1 ? "" : "s"}.`); status = "added"; }
    else if (edit.type === "storage-change") { if (edit.operation === "add") { const additions = Array.from({ length: edit.quantity }, (_, index) => storageComponent(edit, index, project)); project = { ...project, components: [...project.components, ...additions] }; additions.forEach((item) => editedIds.add(item.id)); changes.push(`Added ${edit.quantity} conceptual ${edit.storageType}${edit.quantity === 1 ? "" : "s"}.`); status = "added"; } else { const candidates = project.components.filter((component) => component.name.toLowerCase().includes(edit.storageType)).slice(0, edit.quantity); project = { ...project, components: project.components.filter((component) => !candidates.some((candidate) => candidate.id === component.id)) }; candidates.forEach((item) => editedIds.add(item.id)); changes.push(`Removed ${candidates.length} conceptual ${edit.storageType}${candidates.length === 1 ? "" : "s"}.`); status = "removed"; } tradeoffs.push("Storage additions remain conceptual until a project-specific generator defines joinery and hardware."); }
    else if (edit.type === "component-remove") { const component = resolveEditTarget(project, edit); if (component) { project = { ...project, components: project.components.filter((item) => item.id !== component.id) }; changes.push(`Removed ${component.name}.`); editedIds.add(component.id); status = "removed"; } }
    else if (edit.type === "component-move") { const component = resolveEditTarget(project, edit); if (component) { const current = project.visualization.componentTransforms?.[component.id]?.position ?? { x: 0, y: 0, z: 0 }; const value = edit.operation === "delta" ? current[edit.axis] + edit.value : edit.value; project = { ...project, visualization: { ...project.visualization, componentTransforms: { ...project.visualization.componentTransforms, [component.id]: { ...project.visualization.componentTransforms?.[component.id], position: { ...current, [edit.axis]: value } } } } }; changes.push(`Moved ${component.name} ${Math.abs(edit.value)} inches along the ${edit.axis.toUpperCase()} axis.`); editedIds.add(component.id); } }
    else if (edit.type === "component-resize") { const component = resolveEditTarget(project, edit); if (component) { const dimensionKey = edit.axis === "width" ? "length" : edit.axis; const current = component.dimensions?.[dimensionKey]?.value ?? 0; const value = edit.operation === "delta" ? current + edit.value : edit.value; project = { ...project, components: project.components.map((item) => item.id === component.id ? { ...item, dimensions: { ...item.dimensions, [dimensionKey]: inch(value) } } : item) }; changes.push(`Changed ${component.name} ${edit.axis} from ${current} to ${value} inches.`); editedIds.add(component.id); tradeoffs.push("Component resizing remains conceptual and may alter clearances or support needs."); } }
    else if (edit.type === "component-rename") { const component = resolveEditTarget(project, edit); if (component) { project = { ...project, components: project.components.map((item) => item.id === component.id ? { ...item, name: edit.name } : item) }; changes.push(`Renamed ${component.name} to ${edit.name}.`); editedIds.add(component.id); } }
    else if (edit.type === "constraint-change") { if (edit.constraint === "room-bounds") { const beforeLength = dimensionValue(project, "length"); const beforeDepth = dimensionValue(project, "depth"); project = { ...project, dimensions: { ...project.dimensions, length: inch(Math.min(beforeLength || edit.values.width!, edit.values.width!)), depth: inch(Math.min(beforeDepth || edit.values.depth!, edit.values.depth!)) }, metadata: { ...project.metadata, tags: replaceTag(replaceTag(project.metadata.tags, "room-width:", String(edit.values.width)), "room-depth:", String(edit.values.depth)) } }; changes.push(`Constrained the concept to fit within ${edit.values.width} × ${edit.values.depth} inches.`); editedIds.add("*"); } else if (edit.constraint === "tool-availability") { const tools = Array.isArray(edit.metadata.tools) ? edit.metadata.tools.join(",") : "unspecified"; project = { ...project, metadata: { ...project.metadata, tags: replaceTag(project.metadata.tags, "available-tools:", tools) } }; changes.push(`Remembered available tools: ${tools.replaceAll(",", ", ")}.`); } else { project = { ...project, metadata: { ...project.metadata, tags: replaceTag(project.metadata.tags, `constraint-${edit.constraint}:`, JSON.stringify(edit.values)) } }; changes.push(`Added the ${edit.constraint.replaceAll("-", " ")} concept constraint.`); } }
    else if (edit.type === "budget-target") { project = { ...project, metadata: { ...project.metadata, tags: replaceTag(project.metadata.tags, "budget-target:", edit.direction === "lower" ? "lower" : String(edit.amount ?? "unspecified")) } }; changes.push("Set a lower-cost design preference."); tradeoffs.push("Lower cost may reduce material options, features, or finish complexity."); }
    else if (edit.type === "difficulty-target") { project = { ...project, metadata: { ...project.metadata, tags: replaceTag(project.metadata.tags, "difficulty-target:", edit.targetDifficulty) } }; changes.push(`Set build difficulty preference to ${edit.targetDifficulty}.`); tradeoffs.push("Simplification may remove decorative details or storage features."); }
    else if (edit.type === "safety-target") { const warning = { id: `warning-${edit.id}`, code: "CONCEPT_SAFETY_TARGET", severity: "warning" as const, message: `The concept should be reviewed for ${edit.audience} use, including entrapment, sharp-edge, tip-over, and climbing hazards.`, scope: "project" as const, relatedIds: [], blocking: false }; project = { ...project, intendedUse: { ...project.intendedUse, audience: edit.audience === "toddlers" || edit.audience === "children" ? "child" : "general" }, warnings: project.warnings.some((item) => item.code === warning.code) ? project.warnings : [...project.warnings, warning], metadata: { ...project.metadata, tags: replaceTag(project.metadata.tags, "safety-audience:", edit.audience) } }; changes.push(`Added a ${edit.audience} safety design target.`); concerns.push("This preference is not a safety certification; specialist review and active supervision may still be required."); }
  }
  project = { ...project, visualization: { ...project.visualization, lastEdit: { componentIds: [...editedIds], status, timestamp: edits.at(-1)?.timestamp ?? new Date().toISOString() } } };
  return { project, explanation: { summary: changes.length === 1 ? changes[0]! : `Applied ${changes.length} validated concept changes.`, changes, reason: edits.map((edit) => edit.reason).join(" "), tradeoffs: [...new Set(tradeoffs)], concerns: [...new Set(concerns)] } };
}
