import type { ConversationEditHistory, ConversationEditHistoryEntry, EditorMemory } from "../../../types/conversationEditor";
import type { UniversalWoodProject } from "../../../types/universalProject";
import { emptyEditorMemory } from "./parser";

export function createConversationEditHistory(project: UniversalWoodProject, memory: EditorMemory = emptyEditorMemory(), limit = 30): ConversationEditHistory { return { schemaVersion: 1, initialProject: structuredClone(project), past: [], future: [], memory, limit }; }
export function recordConversationEdit(history: ConversationEditHistory, entry: ConversationEditHistoryEntry): ConversationEditHistory { return { ...history, past: [...history.past, entry].slice(-history.limit), future: [], memory: updateHistoryMemory(history.memory, entry) }; }
export function undoConversationEdit(history: ConversationEditHistory) { const entry = history.past.at(-1); return entry ? { history: { ...history, past: history.past.slice(0, -1), future: [entry, ...history.future] }, project: structuredClone(entry.before) } : { history, project: structuredClone(history.initialProject) }; }
export function redoConversationEdit(history: ConversationEditHistory) { const entry = history.future[0]; return entry ? { history: { ...history, past: [...history.past, entry].slice(-history.limit), future: history.future.slice(1) }, project: structuredClone(entry.after) } : { history, project: structuredClone(history.past.at(-1)?.after ?? history.initialProject) }; }
export function replayConversationEdits(history: ConversationEditHistory) { return structuredClone(history.past.at(-1)?.after ?? history.initialProject); }
export function summarizeConversationEdits(history: ConversationEditHistory) { if (!history.past.length) return "No conversational edits have been applied."; const changes = history.past.flatMap((entry) => entry.explanation.changes); return `${history.past.length} conversation request${history.past.length === 1 ? "" : "s"} applied ${changes.length} validated change${changes.length === 1 ? "" : "s"}: ${changes.join(" ")}`; }

function updateHistoryMemory(memory: EditorMemory, entry: ConversationEditHistoryEntry): EditorMemory { const next = { ...memory, previousEditIds: [...memory.previousEditIds] }; for (const edit of entry.edits) { next.previousEditIds.push(edit.id); if (edit.type === "style-change") next.style = edit.style; if (edit.type === "material-change") next.materials = [edit.material]; if (edit.type === "budget-target") { next.budgetDirection = edit.direction === "lower" ? "lower" : next.budgetDirection; next.budget = edit.amount ?? next.budget; } if (edit.type === "difficulty-target") next.difficulty = edit.targetDifficulty; if (edit.type === "safety-target") next.safetyAudience = edit.audience; if (edit.type === "constraint-change" && edit.constraint === "room-bounds") next.roomSize = { width: edit.values.width!, depth: edit.values.depth! }; if (edit.type === "constraint-change" && edit.constraint === "tool-availability" && Array.isArray(edit.metadata.tools)) next.toolAvailability = [...new Set([...next.toolAvailability, ...edit.metadata.tools.map(String)])]; } return next; }
