import type { ConversationEditRequest, ConversationEditTranslation, EditorMemory, EditClarification, EditTarget, StructuredProjectEdit } from "../../../types/conversationEditor";

const materials = ["pine", "cedar", "pressure-treated", "treated lumber", "oak", "maple", "walnut", "plywood", "mdf", "generic wood"];
const finishes = ["unfinished", "clear coat", "natural stain", "dark stain", "painted white", "painted black", "painted color", "weathered"];
const styles = ["modern", "farmhouse", "craftsman", "minimalist", "rustic", "contemporary", "traditional", "industrial"];
export const emptyEditorMemory = (): EditorMemory => ({ style: null, budget: null, budgetDirection: null, materials: [], roomSize: null, safetyAudience: null, difficulty: null, toolAvailability: [], previousEditIds: [] });

function normalize(text: string) { return text.trim().toLowerCase().replace(/\s+/g, " "); }
function numberFrom(text: string) { const match = text.match(/(-?\d+(?:\.\d+)?)\s*(?:inches|inch|in|\")?/); return match ? Number(match[1]) : null; }
function target(text: string, selectedComponentId?: string | null): EditTarget { if (selectedComponentId && /\b(?:it|this|selected|component)\b/.test(text)) return { scope: "component", id: selectedComponentId }; const names = ["left cabinet", "right cabinet", "cabinet", "shelf", "drawer", "door", "roof", "legs", "leg", "bench", "tabletop", "seat", "post", "beam"]; const selector = names.find((name) => text.includes(name)); return selector ? { scope: "component", selector } : { scope: "project" }; }
function base(type: StructuredProjectEdit["type"], editTarget: EditTarget, reason: string, index: number, timestamp: string) { return { id: `edit-${timestamp.replace(/[^0-9]/g, "")}-${index + 1}`, type, target: editTarget, reason, confidence: 0.9, metadata: {}, timestamp, origin: "user" as const }; }
function clarification(id: string, question: string, reason: string, request: string, options?: string[]): EditClarification { return { id, question, reason, pendingRequest: request, ...(options ? { options } : {}) }; }
function clauses(text: string) { return text.split(/\s*(?:,|\band\b|\bthen\b)\s*/).map((part) => part.trim()).filter(Boolean); }

export class DeterministicConversationEditor {
  translate({ text, memory, selectedComponentId, now = new Date().toISOString() }: ConversationEditRequest): ConversationEditTranslation {
    const normalizedRequest = normalize(text); if (!normalizedRequest) throw new TypeError("Edit request cannot be empty.");
    const edits: StructuredProjectEdit[] = []; let pending: EditClarification | null = null; let index = 0;
    for (const clause of clauses(normalizedRequest)) {
      const editTarget = target(clause, selectedComponentId); const amount = numberFrom(clause); const nextBase = (type: StructuredProjectEdit["type"], reason: string) => base(type, editTarget, reason, index++, now);
      const room = clause.match(/(?:fit|inside|room).*?(\d+(?:\.\d+)?)\s*(?:x|×|by)\s*(\d+(?:\.\d+)?)\s*(ft|feet|foot|'|in|inch|inches|")?/);
      if (room) { const factor = /ft|feet|foot|'/.test(room[3] ?? "") || (!room[3] && Number(room[1]) <= 30 && Number(room[2]) <= 30) ? 12 : 1; edits.push({ ...nextBase("constraint-change", "Fit the project inside the supplied room bounds."), type: "constraint-change", constraint: "room-bounds", values: { width: Number(room[1]) * factor, depth: Number(room[2]) * factor } }); continue; }
      const material = materials.find((item) => clause.includes(item));
      if (material && /\b(?:use|switch|change|material|everything)\b/.test(clause)) { edits.push({ ...nextBase("material-change", `Use ${material} as the material direction.`), type: "material-change", target: { scope: "material" }, material: material === "treated lumber" ? "pressure-treated" : material }); continue; }
      const finish = finishes.find((item) => clause.includes(item));
      if (finish) { edits.push({ ...nextBase("finish-change", `Apply the requested ${finish} finish direction.`), type: "finish-change", target: { scope: "material" }, finish: finish.replaceAll(" ", "-") }); continue; }
      const style = styles.find((item) => clause.includes(item));
      if (style && /\b(?:make|style|look|more)\b/.test(clause)) { edits.push({ ...nextBase("style-change", `Apply a ${style} visual direction.`), type: "style-change", style }); continue; }
      if (/\b(?:wider|narrower|taller|shorter overall|lower overall)\b/.test(clause) && editTarget.scope === "project") { const positive = /wider|taller/.test(clause); if (amount === null) { pending ??= clarification("dimension-amount", `How many inches should I make it ${positive ? /wider/.test(clause) ? "wider" : "taller" : "smaller"}?`, "A relative dimension change needs an amount.", normalizedRequest); continue; } const axis = /taller|lower/.test(clause) ? "height" : "length"; edits.push({ ...nextBase("dimension-change", "Adjust the overall concept proportions."), type: "dimension-change", axis, operation: "delta", value: positive ? amount : -amount, unit: "in" }); continue; }
      if (/\b(?:width|wide|height|tall|depth|deep|length|long)\b/.test(clause) && amount !== null && editTarget.scope === "project") { const axis = /height|tall/.test(clause) ? "height" : /depth|deep/.test(clause) ? "depth" : /length|long/.test(clause) ? "length" : "length"; edits.push({ ...nextBase("dimension-change", "Set the requested overall project dimension."), type: "dimension-change", axis, operation: "set", value: amount, unit: "in" }); continue; }
      if (/\b(?:add|another|more)\b/.test(clause) && /\b(?:drawer|door|shelf|cabinet)\b/.test(clause)) { const storageType = (/drawer|door|shelf|cabinet/.exec(clause)?.[0] ?? "shelf") as "drawer" | "door" | "shelf" | "cabinet"; edits.push({ ...nextBase("storage-change", `Add ${storageType} storage to the concept.`), type: "storage-change", target: { scope: "project" }, storageType, operation: "add", quantity: Math.max(1, amount ?? 1) }); continue; }
      if (/\b(?:remove|take away|delete)\b/.test(clause)) { if (editTarget.scope !== "component") { pending ??= clarification("remove-target", "Which component should I remove?", "The removal target is unclear.", normalizedRequest); continue; } edits.push({ ...nextBase("component-remove", "Remove the requested conceptual component."), type: "component-remove" }); continue; }
      if (/\b(?:move|raise|lower)\b/.test(clause) && editTarget.scope === "component") { if (amount === null) { pending ??= clarification("move-amount", `How many inches should I move the ${editTarget.selector ?? "selected component"}?`, "A component move needs a distance.", normalizedRequest); continue; } const axis = /back|forward/.test(clause) ? "z" : /left|right/.test(clause) ? "x" : "y"; const sign = /lower|left|back/.test(clause) ? -1 : 1; edits.push({ ...nextBase("component-move", "Reposition the requested conceptual component."), type: "component-move", axis, operation: "delta", value: amount * sign, unit: "in" }); continue; }
      if (/\b(?:shorten|lengthen|resize|make .* shorter)\b/.test(clause) && editTarget.scope === "component") { if (amount === null) { pending ??= clarification("resize-amount", `How many inches should I ${/shorten|shorter/.test(clause) ? "shorten" : "resize"} the ${editTarget.selector ?? "selected component"}?`, "A component resize needs an amount.", normalizedRequest); continue; } edits.push({ ...nextBase("component-resize", "Resize the requested conceptual component."), type: "component-resize", axis: "height", operation: "delta", value: /shorten|shorter/.test(clause) ? -amount : amount, unit: "in" }); continue; }
      if (/\b(?:reduce|lower|cut)\b.*\bcost\b|\bcheaper\b/.test(clause)) { edits.push({ ...nextBase("budget-target", "Prefer a lower-cost concept direction."), type: "budget-target", target: { scope: "project" }, direction: "lower" }); continue; }
      if (/\b(?:budget|spend|under|maximum cost)\b/.test(clause) && amount !== null) { edits.push({ ...nextBase("budget-target", "Use the supplied approximate budget target."), type: "budget-target", target: { scope: "project" }, direction: "set", amount }); continue; }
      if (/\b(?:easier|simpler|beginner)\b/.test(clause)) { edits.push({ ...nextBase("difficulty-target", "Prefer a simpler build direction."), type: "difficulty-target", target: { scope: "project" }, targetDifficulty: /beginner/.test(clause) ? "beginner" : "easier" }); continue; }
      const tools = ["circular saw", "miter saw", "table saw", "jigsaw", "drill", "router", "sander", "hand tools"].filter((tool) => clause.includes(tool));
      if (tools.length && /\b(?:have|own|available|tools?)\b/.test(clause)) { edits.push({ ...nextBase("constraint-change", "Remember the tools available for future concept simplification."), type: "constraint-change", target: { scope: "project" }, constraint: "tool-availability", values: {}, metadata: { tools } }); continue; }
      if (/fewer boards/.test(clause)) { edits.push({ ...nextBase("constraint-change", "Reduce conceptual board count where possible."), type: "constraint-change", target: { scope: "project" }, constraint: "board-count", values: { direction: -1 } }); continue; }
      if (/safer.*(?:toddler|child)|(?:toddler|child).*safe/.test(clause)) { edits.push({ ...nextBase("safety-target", "Add child-use safety constraints without claiming verification."), type: "safety-target", target: { scope: "project" }, audience: /toddler/.test(clause) ? "toddlers" : "children" }); continue; }
      if (/\b(?:indoor|outdoor|covered outdoor)\b/.test(clause)) { const environment = clause.includes("covered") ? "covered-outdoor" : clause.includes("outdoor") ? "outdoor" : "indoor"; edits.push({ ...nextBase("environment-change", "Update the intended project environment."), type: "environment-change", target: { scope: "project" }, environment }); continue; }
      pending ??= clarification("unresolved-edit", "What specific dimension, component, material, or style would you like me to change?", "The requested change is not specific enough to validate safely.", normalizedRequest, ["Dimensions", "Component", "Material", "Style"]);
    }
    const nextMemory = updateMemory(memory, edits);
    return { normalizedRequest, edits, clarification: pending, memory: nextMemory };
  }
}

function updateMemory(memory: EditorMemory, edits: StructuredProjectEdit[]): EditorMemory {
  const next: EditorMemory = { ...memory, materials: [...memory.materials], previousEditIds: [...memory.previousEditIds] };
  for (const edit of edits) { next.previousEditIds.push(edit.id); if (edit.type === "style-change") next.style = edit.style; if (edit.type === "material-change") next.materials = [edit.material]; if (edit.type === "budget-target") { next.budgetDirection = edit.direction === "lower" ? "lower" : next.budgetDirection; next.budget = edit.amount ?? next.budget; } if (edit.type === "difficulty-target") next.difficulty = edit.targetDifficulty; if (edit.type === "safety-target") next.safetyAudience = edit.audience; if (edit.type === "constraint-change" && edit.constraint === "room-bounds") next.roomSize = { width: edit.values.width!, depth: edit.values.depth! }; if (edit.type === "constraint-change" && edit.constraint === "tool-availability" && Array.isArray(edit.metadata.tools)) next.toolAvailability = [...new Set([...next.toolAvailability, ...edit.metadata.tools.map(String)])]; }
  return next;
}
