import type { GeneratedBenchPlan } from "../../calculations/bench";
import type { GeneratedProjectPlan } from "../../calculations/projectPlan";
import type { GeneratedTablePlan } from "../../calculations/table";
import type { UniversalBuildStep, UniversalComponent, UniversalConnection, UniversalHardware, UniversalTool, UniversalWoodProject } from "../../types/universalProject";
import { defineUniversalProject } from "./universalProject";

const tools: UniversalTool[] = [
  { id: "tool-tape", name: "Tape measure", category: "measure-layout", required: true },
  { id: "tool-square", name: "Speed square", category: "measure-layout", required: true },
  { id: "tool-saw", name: "Saw", category: "cutting", required: true },
  { id: "tool-drill", name: "Drill / driver", category: "drilling-fastening", required: true },
  { id: "tool-clamps", name: "Clamps", category: "assembly", required: true },
  { id: "tool-sander", name: "Sander or sandpaper", category: "sanding-finishing", required: true },
  { id: "tool-eye", name: "Safety glasses", category: "safety", required: true },
];

function key(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
function inches(value: number) { return { value, unit: "in" as const }; }

function baseAdapter(plan: GeneratedProjectPlan, options: { slug: string; name: string; description: string; style: string; capacity: number; components: Array<{ cutName: string; role: string; structuralRole: UniversalComponent["structuralRole"] }>; connections: (componentIds: Record<string, string>, hardware: UniversalHardware[]) => UniversalConnection[]; buildTime: string; }): UniversalWoodProject {
  const materialId = `material-${plan.material}`;
  const hardware: UniversalHardware[] = plan.hardware.map((item, index) => ({ id: `hardware-${key(item.name)}-${index + 1}`, name: item.name, quantity: item.quantity, unit: item.name.toLowerCase().includes("glue") ? "package" : "piece", specification: "Use the verified generator specification and exterior-rated products where exposed." }));
  const cutList = plan.cutList.map((cut, index) => ({ id: `cut-${key(cut.name)}-${index + 1}`, name: cut.name, componentId: `component-${key(cut.name)}`, materialId, quantity: cut.quantity, dimensions: { length: inches(cut.length), width: inches(cut.width), height: inches(cut.thickness) }, endCut: "square" as const, notes: ["Verify actual lumber dimensions before cutting."] }));
  const components: UniversalComponent[] = options.components.map((item) => { const cuts = cutList.filter((cut) => cut.name === item.cutName); return { id: `component-${key(item.cutName)}`, name: item.cutName, role: item.role, quantity: cuts.reduce((total, cut) => total + cut.quantity, 0), materialIds: [materialId], cutItemIds: cuts.map((cut) => cut.id), structuralRole: item.structuralRole }; });
  const componentIds = Object.fromEntries(components.map((component) => [component.name, component.id]));
  const connections = options.connections(componentIds, hardware);
  const buildSteps: UniversalBuildStep[] = [
    { id: "step-verify", order: 1, title: "Verify plan and stock", instructions: "Confirm configured dimensions and measure the actual lumber before marking cuts.", componentIds: [], cutItemIds: [], hardwareIds: [], toolIds: ["tool-tape", "tool-square", "tool-eye"], dependsOn: [], safetyNotes: ["Nominal and actual lumber dimensions may differ."], verificationChecks: ["Configured dimensions match the intended project."] },
    { id: "step-cut", order: 2, title: "Cut and label parts", instructions: "Cut each verified cut-list item and label it with its component name.", componentIds: components.map((item) => item.id), cutItemIds: cutList.map((item) => item.id), hardwareIds: [], toolIds: ["tool-tape", "tool-square", "tool-saw", "tool-eye"], dependsOn: ["step-verify"], safetyNotes: ["Support stock and follow the tool manufacturer’s instructions."], verificationChecks: ["Quantities and finished cut lengths match the cut list."] },
    { id: "step-assemble", order: 3, title: "Assemble and square", instructions: "Assemble the verified components using the specified connections, checking alignment and diagonals before final tightening.", componentIds: components.map((item) => item.id), cutItemIds: [], hardwareIds: hardware.map((item) => item.id), toolIds: ["tool-drill", "tool-clamps", "tool-square", "tool-eye"], dependsOn: ["step-cut"], safetyNotes: ["Do not continue with a racked or unstable assembly."], verificationChecks: ["Assembly is square, supported, and free of rocking."] },
    { id: "step-finish", order: 4, title: "Sand, finish, and inspect", instructions: "Ease sharp edges, apply an appropriate exterior finish, and perform a final fastener and stability inspection.", componentIds: components.map((item) => item.id), cutItemIds: [], hardwareIds: [], toolIds: ["tool-sander", "tool-eye"], dependsOn: ["step-assemble"], safetyNotes: ["Use suitable dust and finish protection."], verificationChecks: ["No loose fasteners, sharp edges, or instability remain."] },
  ];
  const dimensionMap = Object.fromEntries(plan.dimensions.map((dimension) => [dimension.label.toLowerCase().replace("seat ", ""), inches(dimension.value)]));
  return defineUniversalProject({ schemaVersion: 1, id: `verified:${options.slug}`, slug: options.slug, name: options.name, description: options.description, category: "Furniture", projectType: plan.projectType, riskTier: "nonstructural", verificationStatus: "verified-generator", source: { kind: "verified-generator", id: plan.projectType, version: "1" }, dimensions: dimensionMap, environment: { location: "outdoor", exposure: ["moisture", "sun"], attachment: "freestanding" }, intendedUse: { summary: options.description, capacity: options.capacity, capacityUnit: "people", audience: "general" }, components, connections, materials: [{ id: materialId, name: plan.material, family: "solid-wood", species: plan.material, treatment: plan.material === "treated" ? "pressure-treated" : undefined, quantity: plan.cutList.reduce((total, item) => total + item.quantity, 0), unit: "piece" }], hardware, cutList, tools, buildSteps, visualization: { defaultView: "lifestyle", availableViews: ["lifestyle", "front", "side", "blueprint", "assembly"], dynamic: true, assetRefs: {}, dimensionLabels: plan.dimensions.map((item) => item.label), camera: { orbit: false, pan: true, zoom: true } }, warnings: [{ id: "warning-verify", code: "VERIFY_BEFORE_CUTTING", severity: "warning", message: "Verify every measurement and actual lumber dimension before cutting.", scope: "dimensions", relatedIds: [], blocking: false }, { id: "warning-safety", code: "USER_TOOL_SAFETY", severity: "warning", message: "The user is responsible for safe tool use and appropriate judgment.", scope: "project", relatedIds: [], blocking: false }], verification: { disclaimer: "Verified calculations are limited to Sawly’s deterministic generator assumptions and are not structural engineering certification.", specialistReview: ["none"], assumptions: ["Project is freestanding and used on a level surface.", "Purchased lumber is inspected and actual dimensions are verified."] }, metadata: { tags: ["outdoor", "wood", "verified"], style: options.style, estimatedBuildTime: options.buildTime } });
}

export function adaptOutdoorTablePlan(plan: GeneratedTablePlan): UniversalWoodProject {
  return baseAdapter(plan, { slug: "outdoor-table", name: plan.projectName, description: "A freestanding outdoor dining table.", style: plan.inputs.style, capacity: plan.inputs.length >= 96 ? 10 : plan.inputs.length >= 84 ? 8 : plan.inputs.length >= 72 ? 6 : 4, buildTime: "6–8 hours", components: [{ cutName: "Leg", role: "Vertical supports", structuralRole: "supporting" }, { cutName: "Long Apron", role: "Longitudinal frame", structuralRole: "lateral-stability" }, { cutName: "Short Apron", role: "End frame", structuralRole: "lateral-stability" }, { cutName: "Tabletop Board", role: "Work and dining surface", structuralRole: "supporting" }], connections: (ids, hardware) => [{ id: "connection-table-frame", name: "Screwed and glued apron frame", type: "screw", componentIds: [ids.Leg, ids["Long Apron"], ids["Short Apron"]], hardwareIds: hardware.map((item) => item.id), location: "Leg-to-apron joints", requiresVerification: true }, { id: "connection-tabletop", name: "Tabletop to frame", type: "screw", componentIds: [ids["Tabletop Board"], ids["Long Apron"], ids["Short Apron"]], hardwareIds: hardware.filter((item) => item.name.includes("Screws")).map((item) => item.id), location: "Tabletop underside", requiresVerification: true }] });
}

export function adaptOutdoorBenchPlan(plan: GeneratedBenchPlan): UniversalWoodProject {
  return baseAdapter(plan, { slug: "outdoor-bench", name: plan.projectName, description: "A freestanding outdoor seating bench.", style: plan.inputs.style ?? "modern", capacity: plan.inputs.length >= 96 ? 6 : plan.inputs.length >= 72 ? 4 : 2, buildTime: "4–6 hours", components: [{ cutName: "Leg", role: "Vertical supports", structuralRole: "supporting" }, { cutName: "Long Apron", role: "Longitudinal frame", structuralRole: "lateral-stability" }, { cutName: "Short Apron", role: "End frame", structuralRole: "lateral-stability" }, { cutName: "Seat Board", role: "Seating surface", structuralRole: "supporting" }], connections: (ids, hardware) => [{ id: "connection-bench-frame", name: "Bench apron frame", type: "screw", componentIds: [ids.Leg, ids["Long Apron"], ids["Short Apron"]], hardwareIds: hardware.map((item) => item.id), location: "Leg-to-apron joints", requiresVerification: true }, { id: "connection-seat", name: "Seat boards to frame", type: "screw", componentIds: [ids["Seat Board"], ids["Long Apron"], ids["Short Apron"]], hardwareIds: hardware.filter((item) => !item.name.includes("Glue")).map((item) => item.id), location: "Seat surface", requiresVerification: true }] });
}
