"use client";
import { useMemo, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/Button";
import { ConversationEditingService, createConversationEditHistory, redoConversationEdit, replayConversationEdits, resultToHistory, summarizeConversationEdits, undoConversationEdit } from "@/lib/ai/conversation-editor";
import type { EditClarification, EditExplanation } from "@/types/conversationEditor";
import type { UniversalWoodProject } from "@/types/universalProject";

interface Message { id: string; role: "user" | "assistant"; text: string; details?: EditExplanation; }

export function ConversationEditPanel({ project, selectedComponentId, onApply }: { project: UniversalWoodProject; selectedComponentId: string | null; onApply: (project: UniversalWoodProject, explanation: EditExplanation) => void; }) {
  const service = useMemo(() => new ConversationEditingService(), []); const [input, setInput] = useState(""); const [clarification, setClarification] = useState<EditClarification | null>(null); const [messages, setMessages] = useState<Message[]>([{ id: "welcome", role: "assistant", text: "Tell me what you want to change. I’ll translate it into validated concept edits before the model updates." }]); const [history, setHistory] = useState(() => createConversationEditHistory(project));
  function submit(event: FormEvent) { event.preventDefault(); const answer = input.trim(); if (!answer) return; const request = clarification ? `${clarification.pendingRequest} ${answer}` : answer; const before = project; const result = service.execute({ text: request, project: before, memory: history.memory, selectedComponentId }); setMessages((current) => [...current, { id: `user-${Date.now()}`, role: "user", text: answer }, { id: `assistant-${Date.now()}`, role: "assistant", text: result.explanation.summary, details: result.explanation }]); setInput(""); setClarification(result.clarification); if (result.status === "applied") { setHistory((current) => resultToHistory(current, request, result, before)); onApply(result.project, result.explanation); } }
  function undo() { const result = undoConversationEdit(history); setHistory(result.history); onApply(result.project, { summary: "Undid the latest conversational edit.", changes: [], reason: "User requested undo.", tradeoffs: [], concerns: [] }); setMessages((current) => [...current, { id: `undo-${Date.now()}`, role: "assistant", text: "Undid the latest conversational edit." }]); }
  function redo() { const result = redoConversationEdit(history); setHistory(result.history); onApply(result.project, { summary: "Redid the latest conversational edit.", changes: [], reason: "User requested redo.", tradeoffs: [], concerns: [] }); setMessages((current) => [...current, { id: `redo-${Date.now()}`, role: "assistant", text: "Redid the latest conversational edit." }]); }
  function replay() { const replayed = replayConversationEdits(history); onApply(replayed, { summary: "Replayed the validated conversation history.", changes: history.past.flatMap((entry) => entry.explanation.changes), reason: "User requested conversation replay.", tradeoffs: [], concerns: [] }); setMessages((current) => [...current, { id: `replay-${Date.now()}`, role: "assistant", text: summarizeConversationEdits(history) }]); }
  return <section className="border-b border-[var(--color-border)] bg-[var(--color-canvas-muted)] p-4" aria-label="Conversational design editor"><details open><summary className="cursor-pointer text-sm font-semibold">Edit this concept with Sawly</summary><div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto]"><div><div className="max-h-56 space-y-3 overflow-auto rounded-xl bg-white p-4" aria-live="polite">{messages.map((message) => <div key={message.id} className={message.role === "user" ? "ml-auto max-w-[85%] rounded-xl bg-[var(--color-brand)] px-3 py-2 text-sm text-white" : "max-w-[92%] rounded-xl border border-[var(--color-border)] px-3 py-2 text-sm"}><p>{message.text}</p>{message.details && (message.details.changes.length > 0 || message.details.tradeoffs.length > 0 || message.details.concerns.length > 0) && <details className="mt-2"><summary className="cursor-pointer text-xs font-semibold">Why and tradeoffs</summary>{message.details.changes.map((change) => <p key={change} className="mt-1 text-xs">Changed: {change}</p>)}{message.details.tradeoffs.map((tradeoff) => <p key={tradeoff} className="mt-1 text-xs">Tradeoff: {tradeoff}</p>)}{message.details.concerns.map((concern) => <p key={concern} className="mt-1 text-xs">Concern: {concern}</p>)}</details>}</div>)}</div><form onSubmit={submit} className="mt-3 flex flex-col gap-2 sm:flex-row"><label htmlFor="conversation-edit-input" className="sr-only">Describe a concept change</label><input id="conversation-edit-input" value={input} onChange={(event) => setInput(event.target.value)} className="ds-input flex-1" placeholder={clarification?.question ?? "Try: Make it 8 inches taller and use walnut"} /><Button type="submit" disabled={!input.trim()}>{clarification ? "Answer" : "Apply edit"}</Button></form>{clarification && <p className="mt-2 text-sm font-semibold text-[var(--color-clay)]">{clarification.question}</p>}</div><div className="flex flex-wrap content-start gap-2 lg:max-w-48"><Button variant="secondary" onClick={undo} disabled={!history.past.length}>Undo edit</Button><Button variant="secondary" onClick={redo} disabled={!history.future.length}>Redo edit</Button><Button variant="ghost" onClick={replay} disabled={!history.past.length}>Replay</Button><div className="w-full rounded-xl bg-white p-3 text-xs text-[var(--color-ink-muted)]">{summarizeConversationEdits(history)}</div></div></div></details></section>;
}
