"use client";

import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import Link from "next/link";
import { BrandLogo } from "@/components/BrandLogo";
import { PremiumDesignStudio } from "@/components/PremiumDesignStudio";
import { SiteFooter } from "@/components/SiteFooter";
import { Badge, Tag } from "@/components/ui/Badge";
import { Button, buttonClassName } from "@/components/ui/Button";
import { createUniversalDraft, generateProjectConcepts, planProjectRequest } from "@/lib/ai/projectPlanner";
import { validateUniversalProject } from "@/lib/projects/universalProject";
import type { AIProjectConcept, PlannerAnswers, PlannerQuestion, PlannerQuestionId } from "@/types/aiProjectDesigner";
import type { WoodMaterial } from "@/calculations/materialCatalog";

interface HistoryItem { id: PlannerQuestionId; question: string; answer: string; }
const styles = ["modern", "farmhouse", "craftsman", "minimalist", "rustic", "contemporary"].map((value) => ({ value, label: value[0].toUpperCase() + value.slice(1) }));

export function AIProjectDesigner({ initialPrompt }: { initialPrompt: string }) {
  const [prompt, setPrompt] = useState(initialPrompt);
  const [draftPrompt, setDraftPrompt] = useState(initialPrompt);
  const [answers, setAnswers] = useState<PlannerAnswers>({});
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [streamed, setStreamed] = useState("");
  const [typing, setTyping] = useState(false);
  const [selected, setSelected] = useState<AIProjectConcept | null>(null);
  const [dimensionValues, setDimensionValues] = useState<Record<string, number>>({});
  const planning = useMemo(() => prompt ? planProjectRequest(prompt, answers) : null, [answers, prompt]);
  const concepts = useMemo(() => planning?.complete ? generateProjectConcepts(planning.profile) : [], [planning]);
  const assistantText = planning ? planning.complete ? "I have enough information to create three safe concept directions. These are design drafts—not construction plans." : planning.nextQuestion?.prompt ?? "Tell me a little more about your project." : "Describe anything made primarily from wood, and I’ll help shape the idea one question at a time.";

  useEffect(() => {
    const words = assistantText.split(" "); let index = 0;
    const start = window.setTimeout(() => { setStreamed(""); setTyping(true); }, 0);
    const timer = window.setInterval(() => { index += 1; setStreamed(words.slice(0, index).join(" ")); if (index >= words.length) { window.clearInterval(timer); setTyping(false); } }, 24);
    return () => { window.clearTimeout(start); window.clearInterval(timer); };
  }, [assistantText]);

  function begin(event: FormEvent) { event.preventDefault(); const value = draftPrompt.trim().replace(/\s+/g, " "); if (!value) return; setPrompt(value); setAnswers({}); setHistory([]); setSelected(null); }
  function answerQuestion(value: string) { const question = planning?.nextQuestion; if (!question || typing) return; setAnswers((current) => ({ ...current, [question.id]: value })); setHistory((items) => [...items, { id: question.id, question: question.prompt, answer: value }]); }
  function editAnswer(index: number) { const retained = history.slice(0, index); setHistory(retained); setAnswers(Object.fromEntries(retained.map((item) => [item.id, item.answer])) as PlannerAnswers); setSelected(null); }
  function goBack() { if (!history.length) { setPrompt(""); return; } editAnswer(history.length - 1); }
  function chooseConcept(concept: AIProjectConcept) { if (!planning) return; const project = createUniversalDraft(planning.profile, concept); if (!validateUniversalProject(project).valid) return; setSelected(concept); setDimensionValues(Object.fromEntries(Object.entries(project.dimensions).filter(([key]) => key !== "custom").map(([key, measure]) => [key, typeof measure === "object" && measure && "value" in measure ? measure.value : 0]))); }

  if (selected && planning) {
    const project = createUniversalDraft({ ...planning.profile, dimensions: { ...planning.profile.dimensions, ...Object.fromEntries(Object.entries(dimensionValues).map(([key, value]) => [key, { value, unit: "in" }])) } }, selected);
    const length = dimensionValues.length || 72; const width = dimensionValues.width || dimensionValues.depth || 36; const height = dimensionValues.height || 30;
    const material: WoodMaterial = planning.profile.materials.some((item) => /cedar/i.test(item)) ? "cedar" : planning.profile.materials.some((item) => /treated/i.test(item)) ? "treated" : "pine";
    return <main className="min-h-screen bg-[var(--color-canvas)]"><Header /><div className="ds-container ds-section"><div className="flex flex-wrap items-center justify-between gap-4"><div><Badge tone={project.riskTier === "code-sensitive" ? "clay" : "muted"}>AI concept · not build-verified</Badge><h1 className="ds-heading mt-4">{project.name}</h1><p className="ds-body mt-2 max-w-3xl">{project.description}</p></div><Button variant="secondary" onClick={() => setSelected(null)}>Back to concepts</Button></div>{project.riskTier === "code-sensitive" && <div className="mt-6 rounded-[var(--radius-lg)] border border-[#dfb1a7] bg-[var(--color-clay-soft)] p-5 font-semibold text-[var(--color-danger)]">This project will require additional engineering and/or local code verification before build plans can be generated.</div>}<PremiumDesignStudio project={/bench|seating/.test(project.projectType) ? "bench" : "table"} dimensions={[{ key: "length", label: "Length", value: length, min: 12, max: 360, onChange: (value) => setDimensionValues((current) => ({ ...current, length: Number(value) || 0 })) }, { key: "width", label: "Width", value: width, min: 12, max: 360, onChange: (value) => setDimensionValues((current) => ({ ...current, width: Number(value) || 0 })) }, { key: "height", label: "Height", value: height, min: 12, max: 240, onChange: (value) => setDimensionValues((current) => ({ ...current, height: Number(value) || 0 })) }]} material={material} style={selected.style} styleOptions={styles} onStyleChange={(style) => setSelected((current) => current ? { ...current, style } : current)} versionALabel="Selected concept" versionBLabel="Size study" /><section className="ds-card mt-8 p-6"><h2 className="ds-subheading">Universal project draft</h2><p className="ds-body mt-2">Placeholder geometry only. Cut lists, connections, hardware, and build steps remain empty until a deterministic generator validates this project type.</p><div className="mt-5 flex flex-wrap gap-2"><Tag>{project.category}</Tag><Tag>{project.riskTier}</Tag><Tag>{project.environment.location}</Tag><Tag>{project.metadata.style ?? "Style pending"}</Tag></div></section></div><SiteFooter /></main>;
  }

  return <main className="min-h-screen bg-[var(--color-canvas)]"><Header /><div className="ds-container ds-section"><div className="mx-auto max-w-4xl"><p className="ds-eyebrow">AI Project Designer</p><h1 className="ds-display mt-4">What do you want to build?</h1><p className="ds-body mt-5 max-w-2xl text-lg">Describe anything made primarily from wood. Sawly will organize the idea, ask one question at a time, and create safe concept directions.</p>{!prompt && <form onSubmit={begin} className="ai-prompt-shell mt-9"><label htmlFor="project-designer-prompt" className="sr-only">Describe your wood project</label><textarea id="project-designer-prompt" value={draftPrompt} onChange={(event) => setDraftPrompt(event.target.value)} placeholder="Describe anything made of wood..." rows={4} className="ds-input min-h-36 resize-none text-lg leading-8" /><Button type="submit" className="mt-4 w-full sm:w-auto" disabled={!draftPrompt.trim()}>Generate Concepts</Button><div className="mt-5 flex flex-wrap gap-2">{["Modern TV stand", "Backyard pergola", "Indoor toddler climbing gym", "Chicken coop", "Garage cabinets", "Farmhouse dining table", "Built-in bookshelves", "Outdoor kitchen", "Treehouse"].map((example) => <button type="button" key={example} onClick={() => setDraftPrompt(example)} className="ds-tag cursor-pointer">{example}</button>)}</div></form>}
      {prompt && <div className="mt-9 grid gap-6 lg:grid-cols-[15rem_minmax(0,1fr)]"><aside><div className="ds-card p-5"><p className="ds-caption font-semibold">Design progress</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-[var(--color-canvas-muted)]"><div className="h-full bg-[var(--color-brand)] transition-all" style={{ width: `${planning?.complete ? 100 : Math.min(90, 18 + history.length * 16)}%` }} /></div><p className="ds-caption mt-2">{planning?.complete ? "Ready for concepts" : `${history.length} answers captured`}</p><Button variant="ghost" className="mt-4 w-full" onClick={goBack}>Go back</Button></div></aside><section aria-label="Project design conversation"><div className="space-y-4"><Chat role="user">{prompt}</Chat>{history.map((item, index) => <div key={`${item.id}-${index}`}><Chat role="assistant">{item.question}</Chat><Chat role="user" action={<button type="button" onClick={() => editAnswer(index)} className="text-xs font-semibold underline">Edit</button>}>{item.answer}</Chat></div>)}<Chat role="assistant">{streamed}{typing && <span className="ml-1 inline-block animate-pulse" aria-label="Sawly is typing">●</span>}</Chat></div>{!typing && planning?.nextQuestion && <AnswerInput question={planning.nextQuestion} onAnswer={answerQuestion} />}{planning?.complete && <div className="mt-8"><div className="flex flex-wrap gap-2"><Tag>{planning.profile.category}</Tag><Tag>{planning.profile.riskTier}</Tag>{planning.profile.materials.map((item) => <Tag key={item}>{item}</Tag>)}</div>{planning.profile.riskTier === "code-sensitive" && <div className="mt-5 rounded-[var(--radius-lg)] border border-[#dfb1a7] bg-[var(--color-clay-soft)] p-4 text-sm font-semibold text-[var(--color-danger)]">This project will require additional engineering and/or local code verification before build plans can be generated.</div>}<div className="mt-6 grid gap-5 md:grid-cols-3">{concepts.map((concept) => <article key={concept.id} className="ds-card overflow-hidden"><div className="grid aspect-[4/3] place-items-center bg-gradient-to-br from-[#eadbc7] to-[#c9d2bd] p-5 text-center"><div><p className="font-semibold">{concept.thumbnail.label}</p><p className="ds-caption mt-2">Intentional placeholder</p></div></div><div className="p-5"><h2 className="text-lg font-semibold">{concept.name}</h2><p className="ds-body mt-2 text-sm">{concept.description}</p><div className="mt-4 flex flex-wrap gap-2"><Tag>{concept.estimatedCost}</Tag><Tag>{concept.difficulty}</Tag></div><ul className="mt-4 space-y-1 text-sm text-[var(--color-ink-muted)]">{concept.keyFeatures.map((feature) => <li key={feature}>• {feature}</li>)}</ul><Button className="mt-5 w-full" onClick={() => chooseConcept(concept)}>Open in Design Studio</Button></div></article>)}</div></div>}</section></div>}</div></div><SiteFooter /></main>;
}

function Header() { return <header className="border-b border-[var(--color-border)] bg-[var(--color-surface)]"><div className="ds-container flex items-center justify-between py-4"><BrandLogo /><nav className="flex items-center gap-3"><Link href="/design" className={buttonClassName("ghost")}>Guided templates</Link><Link href="/#catalog" className={buttonClassName("secondary")}>Project catalog</Link></nav></div></header>; }
function Chat({ role, children, action }: { role: "user" | "assistant"; children: ReactNode; action?: ReactNode }) { return <div className={`flex ${role === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-[88%] rounded-2xl px-5 py-4 ${role === "user" ? "bg-[var(--color-brand)] text-white" : "border border-[var(--color-border)] bg-white"}`}><div aria-live={role === "assistant" ? "polite" : undefined}>{children}</div>{action && <div className="mt-2 text-right">{action}</div>}</div></div>; }
function AnswerInput({ question, onAnswer }: { question: PlannerQuestion; onAnswer: (value: string) => void }) { const [value, setValue] = useState(""); if (question.type === "choice") return <div className="mt-5 grid gap-2 sm:grid-cols-2">{question.options?.map((option) => <Button key={option.value} variant="secondary" className="justify-start text-left" onClick={() => onAnswer(option.value)}>{option.label}</Button>)}</div>; return <form className="mt-5 flex flex-col gap-3 sm:flex-row" onSubmit={(event) => { event.preventDefault(); if (value.trim()) { onAnswer(value.trim()); setValue(""); } }}><label className="sr-only" htmlFor={`answer-${question.id}`}>{question.prompt}</label><input id={`answer-${question.id}`} autoFocus value={value} onChange={(event) => setValue(event.target.value)} className="ds-input flex-1" placeholder={question.helpText ?? "Type your answer"} /><Button type="submit" disabled={!value.trim()}>Send</Button></form>; }
