import { isCustomConceptPackage } from "./schema";
import type { CustomConceptPackage, SavedCustomConcept } from "@/types/customConcept";
export const SAVED_CUSTOM_CONCEPTS_KEY = "sawly.custom-concepts.v1";
const workspaceKey = (id: string) => `sawly.concept-workspace:${id}`;
export function storeConceptWorkspace(value: CustomConceptPackage) { window.sessionStorage.setItem(workspaceKey(value.id), JSON.stringify(value)); }
export function readConceptWorkspace(id: string) { try { const value: unknown = JSON.parse(window.sessionStorage.getItem(workspaceKey(id)) ?? "null"); return isCustomConceptPackage(value) ? value : null; } catch { return null; } }
export function readSavedCustomConcepts(): SavedCustomConcept[] { try { const value: unknown = JSON.parse(window.localStorage.getItem(SAVED_CUSTOM_CONCEPTS_KEY) ?? "[]"); return Array.isArray(value) ? value.filter((item): item is SavedCustomConcept => !!item && typeof item === "object" && (item as SavedCustomConcept).schemaVersion === 1 && typeof (item as SavedCustomConcept).id === "string" && isCustomConceptPackage((item as SavedCustomConcept).package)) : []; } catch { return []; } }
export function saveCustomConceptPackage(pack: CustomConceptPackage, selectedConceptId: string | null, revisionHistory: string[] = []) { const current = readSavedCustomConcepts(); const existing = current.find((item) => item.package.id === pack.id); const value: SavedCustomConcept = { schemaVersion: 1, id: existing?.id ?? crypto.randomUUID(), package: pack, selectedConceptId, revisionHistory, savedAt: new Date().toISOString() }; window.localStorage.setItem(SAVED_CUSTOM_CONCEPTS_KEY, JSON.stringify([value,...current.filter((item) => item.id !== value.id)].slice(0,20))); return value; }
export function deleteSavedCustomConcept(id: string) { window.localStorage.setItem(SAVED_CUSTOM_CONCEPTS_KEY, JSON.stringify(readSavedCustomConcepts().filter((item) => item.id !== id))); }
export function duplicateSavedCustomConcept(id: string) { const source = readSavedCustomConcepts().find((item) => item.id === id); if (!source) return null; const copy = { ...source, id: crypto.randomUUID(), package: { ...source.package, id: crypto.randomUUID(), createdAt: new Date().toISOString() }, savedAt: new Date().toISOString() }; window.localStorage.setItem(SAVED_CUSTOM_CONCEPTS_KEY, JSON.stringify([copy,...readSavedCustomConcepts()])); return copy; }
